import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { activeSeasonAt, activeWeeklyEventAt, seasonRewardStates, utcWeekId, WEEK_MS } from '../../shared/seasons.mjs';
import { PlayerProfileStore } from './player-profiles.js';
function store(){return new PlayerProfileStore(join(mkdtempSync(join(tmpdir(),'airport-seasons-')),'profiles.sqlite'));}
const launch=Date.UTC(2026,8,10);

test('active season selection and no-season fallback use UTC time and city',()=>{assert.equal(activeSeasonAt(launch,'dallas')?.seasonId,'season_001_launch');assert.equal(activeSeasonAt(Date.UTC(2027,0,1),'dallas'),undefined);assert.equal(activeSeasonAt(launch,'milwaukee'),undefined);});
test('weekly event rotates on deterministic UTC boundaries',()=>{const season=activeSeasonAt(launch,'dallas')!;assert.equal(utcWeekId(Date.UTC(2026,8,7)),'2026-09-07');assert.notEqual(activeWeeklyEventAt(season,season.startsAt)?.weeklyEventId,activeWeeklyEventAt(season,season.startsAt+WEEK_MS)?.weeklyEventId);});
test('reward state is locked, claimable, then claimed',()=>{const season=activeSeasonAt(launch,'dallas')!;assert.equal(seasonRewardStates(season,0)[0]?.state,'locked');assert.equal(seasonRewardStates(season,100)[0]?.state,'claimable');assert.equal(seasonRewardStates(season,100,['launch-100'])[0]?.state,'claimed');});
test('season points are verified-event idempotent across reconnect',()=>{const db=store();db.getOrCreate('season-pilot','Pilot');assert.equal(db.recordSeasonActivity('season-pilot','dallas','landing','landing:one',1,launch).awarded,true);assert.equal(db.recordSeasonActivity('season-pilot','dallas','landing','landing:one',1,launch).awarded,false);assert.equal(db.getOrCreate('season-pilot','Pilot').season?.points,20);});
test('seasonal missions persist across sessions and award completion once',()=>{const db=store();db.getOrCreate('missions','Pilot');for(let i=0;i<10;i++)db.recordSeasonActivity('missions','dallas','landing',`landing:${i}`,1,launch);const profile=db.getOrCreate('missions','Pilot');assert.equal(profile.season?.missions.find(item=>item.id==='launch-landings')?.completed,true);assert.equal(profile.season?.points,350);});
test('season reward claims are idempotent and unknown rewards are safe',()=>{const db=store();db.getOrCreate('claim','Pilot');for(let i=0;i<5;i++)db.recordSeasonActivity('claim','dallas','event',`event:${i}`,1,launch);const first=db.claimSeasonReward('claim','dallas','launch-100',launch);const credits=first.profile?.credits;assert.equal(first.ok,true);assert.equal(db.claimSeasonReward('claim','dallas','launch-100',launch).profile?.credits,credits);assert.equal(db.claimSeasonReward('claim','dallas','missing',launch).ok,false);});
test('weekly event progresses and pays exactly once',()=>{const db=store();db.getOrCreate('weekly','Pilot');const weekly=activeWeeklyEventAt(activeSeasonAt(launch,'dallas'),launch)!;for(let i=0;i<weekly.target;i++)db.recordSeasonActivity('weekly','dallas',weekly.activity,`weekly:${i}`,1,launch);const before=db.getOrCreate('weekly','Pilot').credits;assert.equal(db.claimWeeklyEventReward('weekly','dallas',weekly.weeklyEventId,launch).ok,true);const after=db.getOrCreate('weekly','Pilot').credits;db.claimWeeklyEventReward('weekly','dallas',weekly.weeklyEventId,launch);assert.equal(db.getOrCreate('weekly','Pilot').credits,after);assert.equal(after-before,weekly.credits);});
test('expired season rejects new progress and existing profiles migrate safely',()=>{const db=store();const existing=db.getOrCreate('existing','Pilot');assert.equal(existing.credits,0);assert.equal(db.recordSeasonActivity('existing','dallas','landing','late',1,Date.UTC(2027,0,1)).awarded,false);});
test('owned limited cosmetics survive season expiry',()=>{const db=store();db.getOrCreate('cosmetic','Pilot');for(let i=0;i<80;i++)db.recordSeasonActivity('cosmetic','dallas','event',`event:${i}`,1,launch);assert.equal(db.claimSeasonReward('cosmetic','dallas','launch-2500',launch).ok,true);assert.equal(db.getOrCreate('cosmetic','Pilot').cosmetics.ownedIds.includes('bluejay-launch'),true);});
