export type RegistryCityId='dallas'|'milwaukee';
export type CityCapabilities={tutorialEnabled:boolean;practiceMode:boolean;progressionEnabled:boolean;territoriesEnabled:boolean;competitiveEnabled:boolean};
export type IntercityRoute={routeId:string;fromCityId:RegistryCityId;toCityId:RegistryCityId;fromAirportId:string;toAirportId:string;distanceLabel:string;recommendedAircraft:string;estimatedFlightTime:number;rewardProfile?:{credits:number};sponsorSlotId?:string;enabled:boolean};
export declare const cityRegistry:Readonly<Record<RegistryCityId,Readonly<Record<string,unknown>>>>;
export declare const cityAliases:Readonly<Record<string,RegistryCityId>>;
export declare function normalizeCityId(value:string):RegistryCityId|undefined;
export declare function cityDefinition(value:string):Readonly<Record<string,unknown>>|undefined;
export declare function cityCapabilities(value:string):Readonly<CityCapabilities>|undefined;
export declare function airportsForCity(value:string):readonly {id:string;x:number;z:number;heading:number;runwayWidth:number;runwayLength:number}[];
export declare const intercityRoutes:readonly IntercityRoute[];
export declare function routeDefinition(routeId:string):IntercityRoute|undefined;
export declare function routesFromCity(cityId:string):IntercityRoute[];
