const limitedCosmetics={
  'decal-first-flight':{availableFrom:Date.UTC(2026,8,1),availableUntil:Date.UTC(2026,8,29),seasonId:'season_001_launch',source:'seasonReward',rarity:'rare',unlockRequirement:500},
  'title-launch-pilot':{availableFrom:Date.UTC(2026,8,1),availableUntil:Date.UTC(2026,8,29),seasonId:'season_001_launch',source:'seasonReward',rarity:'rare',unlockRequirement:250},
  'frame-launch-season':{availableFrom:Date.UTC(2026,8,1),availableUntil:Date.UTC(2026,8,29),seasonId:'season_001_launch',source:'seasonReward',rarity:'rare',unlockRequirement:1300},
  'badge-first-flights-ace':{availableFrom:Date.UTC(2026,8,1),availableUntil:Date.UTC(2026,8,29),seasonId:'season_001_launch',source:'seasonReward',rarity:'epic',unlockRequirement:1800},
  'bluejay-launch':{availableFrom:Date.UTC(2026,8,1),availableUntil:Date.UTC(2026,8,29),seasonId:'season_001_launch',source:'seasonReward',rarity:'legendary',unlockRequirement:2500},
};
export const cosmeticCatalog = [
  ['bluejay-classic','livery','CLASSIC BLUE','trainer','free',0,0,{ primary:0x1769b8, accent:0x73b9e8 }],
  ['bluejay-sunset','livery','SUNSET ORANGE','trainer','credits',2000,0,{ primary:0xd96b27, accent:0xffbf66 }],
  ['bluejay-night','livery','NIGHT BLUE','trainer','credits',3000,0,{ primary:0x172c59, accent:0x5a8edb }],
  ['mammoth-sand','livery','DESERT SAND','cargo','free',0,0,{ primary:0x7e6843, accent:0xd3bd8b }],
  ['mammoth-gray','livery','INDUSTRIAL GRAY','cargo','credits',2500,0,{ primary:0x4d555c, accent:0xaab3b8 }],
  ['mammoth-rescue','livery','RESCUE ORANGE','cargo','credits',3500,0,{ primary:0xc55a19, accent:0xffc04f }],
  ['nightowl-forest','livery','FOREST GREEN','privateJet','free',0,0,{ primary:0x285d3d, accent:0x78a46b }],
  ['nightowl-black','livery','EXECUTIVE BLACK','privateJet','credits',4000,0,{ primary:0x171b20, accent:0x7d8994 }],
  ['nightowl-arctic','livery','ARCTIC WHITE','privateJet','credits',4000,0,{ primary:0xdde8eb, accent:0x77b5c7 }],
  ['firehawk-red','livery','RACING RED','fighter','free',0,0,{ primary:0x6d101b, accent:0xf1d8c5 }],
  ['firehawk-stealth','livery','STEALTH GRAY','fighter','credits',5000,0,{ primary:0x343a40, accent:0x8f9aa3 }],
  ['firehawk-gold','livery','CRIMSON GOLD','fighter','pilotLevel',0,25,{ primary:0x8b1622, accent:0xe7b643 }],
  ['bluejay-crimson','livery','CRIMSON WHITE','trainer','credits',2000,0,{base:0xf4f2ec,primary:0xb91e3d,accent:0xe85f6c}],
  ['bluejay-gold','livery','GOLD NAVY','trainer','credits',2500,0,{base:0x192b4c,primary:0xe7b743,accent:0xf7db82}],
  ['bluejay-silver','livery','SILVER GLASS','trainer','credits',2000,0,{base:0xc7d5df,primary:0x718f9f,accent:0xe5f8ff}],
  ['bluejay-rescue','livery','RESCUE GREEN','trainer','credits',2000,0,{base:0xf0f4e8,primary:0x238855,accent:0xb7ed6a}],
  ['bluejay-purple','livery','PURPLE NIGHT','trainer','credits',2500,0,{base:0x38385b,primary:0x975cda,accent:0xdfb4ff}],
  ['bluejay-white-red','livery','WHITE RED','trainer','credits',2000,0,{base:0xffffff,primary:0xe74345,accent:0x9b1b35}],
  ['bluejay-cyan','livery','CYAN TECH','trainer','credits',2500,0,{base:0x223b56,primary:0x36d2e2,accent:0xddfaff}],
  ['bluejay-desert','livery','DESERT TAN','trainer','credits',2000,0,{base:0xd9c7a3,primary:0x96764b,accent:0xf6e3bb}],
  ['contrail-none','contrail','NONE',null,'free',0,0,{ color:null }],
  ['contrail-white','contrail','WHITE',null,'credits',1500,0,{ color:0xffffff }],
  ['contrail-cyan','contrail','CYAN',null,'credits',2500,0,{ color:0x54dff2 }],
  ['contrail-crimson','contrail','CRIMSON',null,'credits',3500,0,{ color:0xc81f42 }],
  ['contrail-gold','contrail','GOLD',null,'pilotLevel',0,35,{ color:0xf4c542 }],
  ['badge-secret-hunter','badge','SECRET HUNTER',null,'achievement',0,0,{}],
  ['badge-weekly-ace','badge','WEEKLY ACE',null,'achievement',0,0,{}],
  ['badge-ace-pilot','badge','ACE PILOT',null,'pilotLevel',0,15,{}],
  ['decal-first-flight','badge','FIRST FLIGHT DECAL',null,'achievement',0,0,{}],
  ['title-launch-pilot','badge','LAUNCH PILOT',null,'achievement',0,0,{}],
  ['frame-launch-season','badge','LAUNCH PHOTO FRAME',null,'achievement',0,0,{}],
  ['badge-first-flights-ace','badge','FIRST FLIGHTS ACE',null,'achievement',0,0,{}],
  ['bluejay-launch','livery','LAUNCH BLUE', 'trainer','achievement',0,0,{ primary:0x1458a6, accent:0xf4c542 }],
].map(([id,category,displayName,aircraftRestriction,unlockType,creditPrice,requiredLevel,visualConfig])=>({id,category,displayName,description:displayName,aircraftRestriction,unlockType,creditPrice,requiredLevel,visualConfig,...(limitedCosmetics[id]??{})}));
export const defaultCosmeticIds=['bluejay-classic','mammoth-sand','nightowl-forest','firehawk-red','contrail-none'];
