export const PROTOCOL_VERSION: number;
export const COMBAT_RANGE: number;
export function ballisticShotSpeed(velocity: { x: number; y: number; z: number }, direction: { x: number; y: number; z: number }): number;
export const LOCK_ANGLE: number;
export const AIM_ENVELOPE: number;
export const AIM_MAX_OFFSET: number;
export const AIM_MANUAL_OFFSET: number;
export const AIM_SWITCH_MARGIN: number;
export type AimOffset = { x: number; y: number };
export function interpolateAim(from: AimOffset, to: AimOffset, blend: number, out: AimOffset): AimOffset;
export function aimTargetScore(angle: number, distance: number): number;
export function aimGoal(x: number, y: number, z: number, out: AimOffset): boolean;
export function biasAimVertically(goal: AimOffset, input: unknown): void;
export function stepAim(aim: AimOffset, goal: AimOffset, delta: number, maxOffset?: number): void;
export function insideDynamicLock(x: number, y: number, z: number, aim: AimOffset): boolean;
