export declare const TUTORIAL_VERSION: 'tutorial_v1';
export declare const tutorialSteps: readonly ['throttle', 'takeoff', 'turnLeft', 'turnRight', 'climb', 'descend', 'cameraLook', 'cameraZoom', 'approach', 'targetLock', 'fire', 'landing'];
export type TutorialStep = typeof tutorialSteps[number] | 'freePractice';
export type TutorialLessonStep = typeof tutorialSteps[number];
export type TutorialStepStatus = 'pending' | 'completed' | 'skipped';
export type TutorialStatus = 'new' | 'started' | 'completed' | 'skipped';
export declare function normalizeTutorialState(value: unknown): { version: 'tutorial_v1'; status: TutorialStatus; completedAt?: number };
export declare function nextTutorialStep(step: string, signal: string): string;
export declare function tutorialTurnProgress(step: 'turnLeft' | 'turnRight' | string, headingDelta: number): number;
export declare function tutorialStepPrerequisitesResolved(step: TutorialLessonStep, states: Partial<Record<TutorialLessonStep, TutorialStepStatus>>): boolean;
export type TutorialInputMode = 'keyboard' | 'touch';
export type TutorialBindings = Partial<Record<'throttleUp' | 'throttleDown' | 'pitchUp' | 'pitchDown' | 'turnLeft' | 'turnRight' | 'aimLeft' | 'aimRight' | 'aimUp' | 'aimDown' | 'fire' | 'cameraLook' | 'cameraZoom', string>>;
export type TutorialInstruction = Readonly<{ lesson: number; title: string; explanation: string; controlInstruction: string; control: string }>;
export declare function tutorialInstruction(step: string, inputMode?: TutorialInputMode, inverted?: boolean, bindings?: TutorialBindings): TutorialInstruction;
export declare function tutorialLockPreviewInstruction(): TutorialInstruction;
export declare function tutorialTakeoffRecoveryInstruction(step: TutorialLessonStep, inputMode?: TutorialInputMode, inverted?: boolean, bindings?: TutorialBindings): TutorialInstruction;
export declare function tutorialDetectedInstruction(step: string, inputMode?: TutorialInputMode, inverted?: boolean, bindings?: TutorialBindings, landingStage?: 'power' | 'alignment' | 'descent'): string;
export declare function tutorialLandingInstruction(stage: 'power' | 'alignment' | 'descent', inputMode?: TutorialInputMode, inverted?: boolean, bindings?: TutorialBindings): TutorialInstruction;
export declare function shouldOfferTutorial(status?: string, establishedProfile?: boolean, localStatus?: string | null): boolean;
